services:
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    restart: always
    depends_on:
      - php
      - mysql
    networks:
      - minharede
    volumes:
      - ./src/app:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  php:
    build:
      context: ./docker/php
    container_name: php
    restart: always
    depends_on:
        - mysql
    volumes:
        - ./src/app:/var/www/app/
    ports:
      - 9000:9000
    networks:
        - minharede
  mysql:
    image: mysql:8.0.39-debian
    container_name: mysql
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lemp
      MYSQL_USER: lemp
      MYSQL_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    networks:
      - minharede
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - minharede
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - minharede
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/usr/local/etc/redis/redis.conf
networks:
  minharede:
    driver: bridge